'use client';
import {useEffect,useState} from 'react';
import '../field/field.css';
type Card={name:string;city:string;state:string;proof:{title:string;quote:string;sourceUrl?:string}[];schedulingPhone:string};
export default function VisitPage(){
  const [card,setCard]=useState<Card|null>(null),[code,setCode]=useState(''),[error,setError]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[consent,setConsent]=useState(false),[website,setWebsite]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
  useEffect(()=>{let alive=true;const value=new URLSearchParams(location.search).get('code')||'';setCode(value);if(!value){setError('Open the link on your Raydar card.');return;}void fetch(`/api/field-recovery?code=${encodeURIComponent(value)}`,{cache:'no-store',referrerPolicy:'no-referrer'}).then(async r=>{const data=await r.json();if(!r.ok)throw Error(data.error||'This card is unavailable.');if(alive)setCard(data);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/field-recovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'callback',code,name,phone,consent,website}),referrerPolicy:'no-referrer'}),d=await r.json();if(!r.ok)throw Error(d.error||'Request unavailable.');setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <main className="rf-visit"><div className="rf-brand">Raydar <small>by Happy Solar</small></div>{card?<><span className="rf-kicker">LET’S CONTINUE THE CONVERSATION</span><h1>Curious about solar?</h1><p>{card.name} stopped by your neighborhood in {card.city}. Our scheduling team can help arrange a conversation with a solar consultant.</p>{done?<div className="rf-card"><h2>We received your request.</h2><p>Our team will follow up. Your appointment is confirmed only after you speak with the scheduling manager.</p></div>:<form onSubmit={submit}><label>Your name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} required autoComplete="name"/></label><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value)} maxLength={25} type="tel" required autoComplete="tel"/></label><label className="rf-honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label><label className="rf-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>I ask Happy Solar to call me once about a solar consultation. This is not permission for marketing texts.</span></label><button className="rf-primary" disabled={busy||!consent}>{busy?'Sending…':'Request a callback'}</button></form>}{card.schedulingPhone&&<a className="rf-button" href={`tel:${card.schedulingPhone}`}>Call our scheduling team</a>}{card.proof.map((p,i)=><article className="rf-card" key={i}><h2>{p.title}</h2><p>{p.quote}</p>{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">View source</a>}</article>)}</>:!error&&<p>Opening your card…</p>}{error&&<p className="rf-notice" role="alert">{error}</p>}<small>Your contact details go to Happy Solar for this callback request. No payment or purchase is required.</small></main>;
}
